-- Oracle DDL for auth schema
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE USERS (
  ID NUMBER(19) PRIMARY KEY,
  USERNAME VARCHAR2(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(255) NOT NULL,
  ENABLED NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE ROLES (
  ID NUMBER(19) PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE USER_ROLES (
  USER_ID NUMBER(19) NOT NULL,
  ROLE_ID NUMBER(19) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);
