-- Seed default roles for SADAD workflow
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ENTRY');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'APPROVER');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'RELEASE');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ADMIN');
